groups/urls.py
from django.contrib import admin  # noqa
from django.urls import path

from groups.views import GroupCreateView, GroupUpdateView, delete_group, get_groups, view_group

from students.views import hello

app_name = 'groups'

urlpatterns = [
    path('', hello, name="hello"),
    path('create', GroupCreateView.as_view(), name="create"),
    path('list/', get_groups, name="list"),
    path('view/<int:id>', view_group, name="view"),
    path('edit/<int:id>', GroupUpdateView.as_view(), name="edit"),
    path('delete/<int:id>', delete_group, name="delete"),
 ]

lms/urls.py
import debug_toolbar

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('groups/', include('groups.urls')),
    path('accounts/', include('accounts.urls')),


]
urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groups/models.py
import datetime

from django.core.exceptions import ValidationError
from django.db import models

from students.models import Student


class Group(models.Model):
    group_name = models.CharField(max_length=25, null=False, blank=False)
    course_name = models.CharField(max_length=85, null=False, blank=False)
    date_start_course = models.DateField(default=datetime.date.today, blank=False)
    teacher = models.ForeignKey(
        to="teachers.Teacher",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='groups'
    )
    head = models.OneToOneField(
        to='students.Student',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='head_of_group'
    )

    def __str__(self):
        return f'{self.id}, {self.group_name}, {self.course_name}, {self.date_start_course}'

    def save(self, *args, **kwargs):
        self.clean_head()
        super().save(*args, **kwargs)

    def clean_head(self):
        head = self.head
        if head is not None:
            st_group = Student.objects.filter(group_id=self.id)
            if head not in st_group:
                raise ValidationError('not in this group')
            return head

groups/forms.py
from django.forms import CharField, DateField, DateInput, ModelForm, forms

from groups.models import Group


class GroupFormCreate(ModelForm):
    class Meta:
        model = Group
        fields = '__all__'
        widgets = {'date_start_course': DateInput(attrs={'type': 'date'})}


class GroupFormList(forms.Form):
    group_name = CharField(label='Group name', required=False)
    course_name = CharField(label='Course name', required=False)
    date_start_course = DateField(widget=DateInput(attrs={'type': 'date'}), label='Start course date', required=False)

    def get_groups(self, request):

        groups = Group.objects.all()

        fields = [field for field in self.fields]

        for field in fields:
            value = request.GET.get(field)
            if value:
                groups = groups.filter(**{field: value})

        return groups

groups/views.py
from core.utils import get_paginator

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy

from django.shortcuts import render, get_object_or_404  # noqa
from django.views.generic import CreateView, UpdateView


from groups.forms import GroupFormCreate, GroupFormList
from groups.models import Group

from students.forms import ViewsStudentsForm


def create_group(request):
    if request.method == "GET":
        form = GroupFormCreate()
    elif request.method == "POST":
        form = GroupFormCreate(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("groups:list"))
    return render(
            request=request,
            template_name='groups-create.html',
            context={'form': form}
        )


def get_groups(request):
    form = GroupFormList()
    if not request.GET:
        groups = Group.objects.all()
    groups = form.get_groups(request)

    return render(
        request=request,
        template_name='groups-list.html',
        context={
            'form': form,
            'groups': get_paginator(groups, request)

            }
        )


def view_group(request, id): # noqa
    try:
        group = Group.objects.get(id=id)
    except Group.DoesNotExist:
        return HttpResponse("Group doesn't exist", status=404)

    if request.method == 'GET':
        form = GroupFormCreate(instance=group)
        st_form = ViewsStudentsForm(request)
        students = st_form.view_students(request=request, group_id=id)
        return render(
            request=request,
            template_name='g-view.html',
            context={
                'form': form,
                'groups': group,
                'students': get_paginator(students, request),

                }
            )

def edit_groups(request, id): # noqa
    try:
        group = Group.objects.get(id=id)
    except Group.DoesNotExist:
        return HttpResponse("Group doesn't exist", status=404)

    if request.method == 'GET':

        form = GroupFormCreate(instance=group)

    elif request.method == 'POST':

        form = GroupFormCreate(
            data=request.POST,
            instance=group
        )

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('groups:list'))

    return render(
        request=request,
        template_name='groups-edit.html',
        context={
            'form': form,
            'group': group,

        }
    )


class GroupCreateView(LoginRequiredMixin, CreateView):
    model = Group
    form_class = GroupFormCreate
    template_name = 'groups-create.html'
    success_url = reverse_lazy('groups:list')
    context_object_name = 'group'


class GroupUpdateView(LoginRequiredMixin, UpdateView):
    model = Group
    form_class = GroupFormCreate
    template_name = 'groups-edit.html'
    success_url = reverse_lazy('groups:list')
    context_object_name = 'group'
    pk_url_kwarg = 'id'


def delete_group(request, id): # noqa
    group = get_object_or_404(Group, id=id)
    group.delete()
    return HttpResponseRedirect(reverse('groups:list'))

groups/templates/g-view.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Groups detail</title>
{% endblock %}

{% block content %}
<h2>Groups</h2>
     <form>
     {% csrf_token %}
     {{form|crispy}}
     </form>
<h3>Group students {{students.count}} </h3>
    {% if not students %}
        <a>Group havn't students </a>
    {% else %}
        {% include 'includes/s_table.html' %}
    {% endif %}
{% endblock %}

groups/templates/groups-create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Create group</title>
{% endblock %}

{% block content %}
<h2>Groups</h2>
  <form method="post">
      {% csrf_token %}
      {{form|crispy}}<br> <br>
      <input class="btn btn-primary" type="submit" value="Create"><br><br>
  </form>
{% endblock %}

groups/templates/groups-edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Groups edit</title>
{% endblock %}

{% block content %}
<h2>Groups</h2>
     <form method="post">
     {% csrf_token %}
     {{form|crispy}}<br> <br>
     <input class="btn btn-success" type="submit" value="Save">
     <input class="btn btn-danger" formaction="{% url 'groups:delete' group.id %}" type="submit" value="Delete">
         <h3>Group current edition</h3>
     <table>
              <tr>
                 <th>Id</th>
                 <th>Name</th>
                 <th>Course</th>
                 <th>Start course</th>
                 <th>Teacher</th>
              </tr>

             <tr>
                 <td>{{ group.id }}</td>
                 <td>{{ group.group_name }}</td>
                 <td>{{ group.course_name }}</td>
                 <td>{{ group.date_start_course }}</td>
                 <td>{{ group.teacher.full_name }}</td>
             </tr>
     </table>
     </form>
{% endblock %}

groups/templates/groups-list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
<title xmlns="http://www.w3.org/1999/html">Groups list</title>
{% endblock %}

{% block content %}
<h2>Groups</h2>
<form>
  {{form|crispy}}<br> <br>
  <input class="btn btn-light" type="submit" value="Search">
  <input class="btn btn-primary" formaction="{% url 'groups:create' %}" type="submit" value = 'Create'><br><br>
  </form>


{% include 'includes/g-table.html' %}

{% endblock %}