accounts/urls.py
from accounts.views import AccountCreateView, AccountLoginView, AccountLogoutView,  AccountPasswordUpdate, \
    AccountUpdateView

from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('register/', AccountCreateView.as_view(), name="register"),
    path('login/', AccountLoginView.as_view(), name="login"),
    path('logout/', AccountLogoutView.as_view(), name="logout"),
    path('profile/', AccountUpdateView.as_view(), name="profile"),
    path('password/', AccountPasswordUpdate.as_view(), name="password"),


 ]

core/urls.py
from core.views import index

from django.contrib import admin  # noqa
from django.urls import path

app_name = 'core'

urlpatterns = [
  path('', index, name="index"),

 ]

lms/urls.py
import debug_toolbar

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('groups/', include('groups.urls')),
    path('accounts/', include('accounts.urls')),


]
urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from core import utils

from PIL import Image  # noqa

from django.contrib.auth.models import User
from django.db import models


class UserAction(models.Model):
    class USER_ACTION(models.IntegerChoices):
        LOGIN = 0, "Login"
        LOGOUT = 1, "Logout"
        CHANGE_PASSWORD = 2, "Change Password"
        CHANGE_PROFILE = 3, "Change Profile"
        CHANGE_PROFILE_IMAGE = 4, "Change Profile Image"

    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    write_date = models.DateTimeField(auto_now_add=True)
    action = models.PositiveSmallIntegerField(choices=USER_ACTION.choices)
    info = models.CharField(max_length=128, null=True)


class Profile(models.Model):
    MAX_SIZE_IMAGE = 300
    user = models.OneToOneField(
        to=User,
        on_delete=models.CASCADE,
        related_name="profile"
    )
    image = models.ImageField(null=True, default='default.jpg', upload_to='pics/')
    interests = models.CharField(max_length=128, null=True)

    def save(self, *args, **kwargs):

        result = super().save()
        utils.resize_image(self.image, self.MAX_SIZE_IMAGE)
        return result

accounts/forms.py
from accounts.models import Profile

from django.contrib.auth.forms import PasswordChangeForm, UserChangeForm, UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm


class AccountCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', "first_name", 'last_name']


class AccountUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = '__all__'


class AccountProfileUpdateForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['image', 'interests']


class AccountChangeForm(PasswordChangeForm):
    class Meta:
        model = User
        fields = ['old_password', 'new_password1', 'new_password2']

accounts/views.py
from accounts.forms import AccountChangeForm, AccountCreateForm, AccountProfileUpdateForm, AccountUpdateForm
from accounts.models import Profile, UserAction

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView


class AccountCreateView(CreateView):
    model = User
    template_name = 'registration.html'
    form_class = AccountCreateForm
    success_url = reverse_lazy('accounts:login')

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, "User successfully created")
        return result


class AccountLoginView(LoginView):
    template_name = 'login.html'

    def get_redirect_url(self):
        if self.request.GET.get('next'):
            return self.request.GET.get('next')
        return reverse('core:index')

    def form_valid(self, form):
        result = super().form_valid(form)
        try:
            profile = self.request.user.profile
        except Exception as ex:  # noqa
            profile = Profile.objects.create(user=self.request.user)
            profile.save()
        user = form.get_user()
        action = UserAction.USER_ACTION.LOGIN
        logged_user = UserAction.objects.create(user=user, action=action)
        logged_user.save()
        messages.success(self.request, f'User {self.request.user.username} is logged')
        return result


class AccountLogoutView(LogoutView):
    template_name = 'logout.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.success(request, f'{self.request.user.username} successfully logged out')
        else:
            messages.error(request, f'{self.request.user.username} your error message')
        return super().dispatch(request, *args, **kwargs)


class AccountUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'profile.html'
    form_class = AccountUpdateForm
    success_url = reverse_lazy('core:index')

    def get_object(self, queryset=None):
        return self.request.user

    def get(self, request, *args, **kwargs):
        user = self.request.user
        profile = self.request.user.profile

        user_form = AccountUpdateForm(instance=user)
        profile_form = AccountProfileUpdateForm(instance=profile)

        return render(
            request=request,
            template_name='profile.html',
            context={
                'user_form': user_form,
                'profile_form': profile_form,
            }
        )

    def post(self, request, *args, **kwargs):
        user = self.request.user
        profile = self.request.user.profile

        user_form = AccountUpdateForm(
            data=request.POST,
            instance=user
        )
        profile_form = AccountProfileUpdateForm(
            data=request.POST,
            files=request.FILES,
            instance=profile
        )

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            old_image = Profile.objects.get(user=self.request.user).image
            profile_form.save()
            if old_image != self.request.user.profile.image:
                messages.info(request, 'Changed the image')
                user = self.request.user
                action = UserAction.USER_ACTION.CHANGE_PROFILE_IMAGE
                changed_image = UserAction.objects.create(user=user,
                                                          action=action,
                                                          info=f"{old_image} => {self.request.user.profile.image}"
                                                          )
                changed_image.save()
            messages.success(request, f"{self.request.user.username}'s profile successfully updated")
            return HttpResponseRedirect(reverse('accounts:profile'))

        return render(
            request=request,
            template_name='profile.html',
            context={
                'user_form': user_form,
                'profile_form': profile_form,
            }
        )


class AccountPasswordUpdate(PasswordChangeView):
    model = User
    template_name = 'password_change_form.html'
    form_class = AccountChangeForm
    success_url = reverse_lazy('accounts:profile')

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, f"{self.request.user.username}'s password is changed")
        return result

accounts/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Login user</title>
{% endblock %}

{% block content %}
<h2>Log in user</h2>

     <form method="post">
     {% csrf_token %}

     {{form|crispy}}<br> <br>

     <input class="btn btn-success" type="submit" value="Login">
         <a class="btn btn-light" href="{% url 'core:index' %}">Home</a>

     </form>
{% endblock %}

accounts/templates/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>User logout</title>
{% endblock %}

{% block content %}

         <a class="btn btn-success" href="{% url 'accounts:login' %}">Login</a>
         <a class="btn btn-light" href="{% url 'core:index' %}">Home</a>

{% endblock %}

accounts/templates/password_change_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Profile user</title>
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">

        {% csrf_token %}

        {{form|crispy}}


        <input class="btn btn-success" type="submit" value="Save">
        <a class="btn btn-light" href="{% url 'core:index' %}">Cancel</a>
    </form>
{% endblock %}

accounts/templates/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Profile user</title>
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">

        <div class="media">
            <div class="img-circle.vert">
                <img class="rounded-circle p-1 m-1" width="200" height="200"  src="{{ user.profile.image.url }}">
            </div>
    {#        <img class="rounded-circle p-1 m-1" width="300" height="{{ user.profile.image.height }}"  src="{{ user.profile.image.url }}">#}
    {#        <img class="img-circle p-1 m-1"  src="{{ user.profile.image.url }}">#}
            <div class="media-body  p-3 m-3">
                <h2 class="account-heading">{{ user.username }}</h2>
                <h3 class="account-heading">{{ user.first_name }} {{ user.last_name }}</h3>
                <p class="text-secondary">{{ user.email }}</p>
            </div>
        </div>


        {% csrf_token %}

        {{user_form|crispy}}
        <div class = 'mb-3'>
            Raw passwords are not stored, you can change the password
            <a href="{% url 'accounts:password' %}">this form</a>
        </div>
        {{ profile_form|crispy }}

        <input class="btn btn-success" type="submit" value="Save">
        <a class="btn btn-light" href="{% url 'core:index' %}">Cancel</a>
    </form>
{% endblock %}

accounts/templates/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Register new user</title>
{% endblock %}

{% block content %}
<h2>Groups</h2>

     <form method="post">
     {% csrf_token %}

     {{form|crispy}}<br> <br>

     <input class="btn btn-success" type="submit" value="Register">
         <a class="btn btn-light" href="{% url 'core:index' %}">Home</a>

     </form>
{% endblock %}