lms/urls.py
import debug_toolbar

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('groups/', include('groups.urls')),
    path('accounts/', include('accounts.urls')),


]
urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teachers/urls.py
from django.contrib import admin  # noqa
from django.urls import path

from teachers.views import TeacherCreateView, TeacherUpdateView, delete_teacher, get_teachers, view_teachers

app_name = 'teachers'

urlpatterns = [
     path('list', get_teachers, name="list"),
     path('create', TeacherCreateView.as_view(), name="create"),
     path('edit/<int:id>', TeacherUpdateView.as_view(), name="edit"),
     path('delete/<int:id>', delete_teacher, name="delete"),
     path('view/<int:id>', view_teachers, name="view"),

 ]

teachers/models.py
import datetime

from django.db import models


class Teacher(models.Model):
    first_name = models.CharField(max_length=64, null=False, blank=False)
    last_name = models.CharField(max_length=64, null=False, blank=False)
    age = models.SmallIntegerField(null=True, blank=True)
    date_start_work = models.DateField(null=True, default=datetime.date.today, blank=True)
    school = models.CharField(max_length=64, null=True, blank=True)

    def full_name(self):
        return f'{self.first_name}, {self.last_name}'

    def __str__(self):
        return f'{self.id}, {self.full_name()}, {self.age}, {self.date_start_work}, {self.school}'

teachers/forms.py
from django.forms import CharField, DateField, DateInput, IntegerField, ModelForm, forms

from teachers.models import Teacher


class TeacherFormCreate(ModelForm):
    class Meta:
        model = Teacher
        fields = (
            'first_name',
            'last_name',
            'age',
            'date_start_work',
            'school'
        )
        widgets = {'date_start_work': DateInput(attrs={'type': 'date'})}


class TeachersFormList(forms.Form):
    first_name = CharField(label='First_name', required=False)
    last_name = CharField(label='Last name', required=False)
    age = IntegerField(label='Age', required=False)
    school = CharField(label='School', required=False)
    date_start_work = DateField(widget=DateInput(attrs={'type': 'date'}), label='Start work date', required=False)

    def get_teachers(self, request):

        teachers = Teacher.objects.all()

        fields = [field for field in self.fields]

        for field in fields:
            value = request.GET.get(field)
            if value:
                teachers = teachers.filter(**{field: value})
        return teachers

    def view_teacher(self, request, id): # noqa
        teachers = Teacher.objects.filter(id=id)

        fields = [field for field in self.fields]

        for field in fields:
            value = request.GET.get(field)
            if value:
                teachers = teachers.filter(**{field: value})

        return teachers

teachers/views.py
from core.utils import get_paginator

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView

from groups.models import Group

from teachers.forms import TeacherFormCreate, TeachersFormList
from teachers.models import Teacher


def get_teachers(request):

    form = TeachersFormList()
    if not request.GET:
        teachers = Teacher.objects.all()
    teachers = form.get_teachers(request)
    return render(
        request=request,
        template_name='teachers-list.html',
        context={
            'form': form,
            'teachers': get_paginator(teachers, request)
        }
        )


def view_teachers(request, id): # noqa
    try:
        teacher = Teacher.objects.get(id=id)
    except Teacher.DoesNotExist:
        return HttpResponse("Group doesn't exist", status=404)

    form = TeacherFormCreate(instance=teacher)
    tc_form = TeachersFormList(request)
    teachers = tc_form.view_teacher(request=request, id=id)
    groups = Group.objects.filter(teacher_id=teacher.id)
    return render(
        request=request,
        template_name='t_view.html',
        context={
            'form': form,
            'teachers': teachers,
            'groups': groups
        }
        )


class TeacherCreateView(LoginRequiredMixin, CreateView):
    model = Teacher
    form_class = TeacherFormCreate
    template_name = 'teachers-create.html'
    success_url = reverse_lazy('teachers:list')
    context_object_name = 'teacher'


class TeacherUpdateView(LoginRequiredMixin, UpdateView):
    login_url = "accounts:login"
    model = Teacher
    form_class = TeacherFormCreate
    template_name = 'teachers-edit.html'
    success_url = reverse_lazy('teachers:list')
    context_object_name = 'teacher'
    pk_url_kwarg = 'id'


def delete_teacher(request, id): # noqa
    teacher = get_object_or_404(Teacher, id=id)
    teacher.delete()
    return HttpResponseRedirect(reverse('teachers:list'))

teachers/templates/t_view.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>View teacher</title>
{% endblock %}

{% block content %}
<h2>Teachers</h2>
<form>
      {% csrf_token %}
      {{form|crispy}}<br>

    <br>

<h3>Groups {{groups.count}}</h3>
    {% if not groups %}
    <a>Teacher hevn't groups</a>
    {% else %}
    {% include 'includes/g-table.html' %}
    {% endif %}

</form>

{% endblock %}

teachers/templates/teachers-create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Create teacher</title>
{% endblock %}

{% block content %}
<h2>Teachers</h2>
<form method="post">
      {% csrf_token %}
      {{form|crispy}}<br> <br>
      <input class="btn btn-primary" type="submit" value="Create"><br><br>
</form>

{% endblock %}

teachers/templates/teachers-edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Create teacher</title>
{% endblock %}

{% block content %}
<h2>Teachers</h2>
<form method="post">
      {% csrf_token %}
      {{form|crispy}}<br>
      <input class="btn btn-success" type="submit" value="Save">
      <input class="btn btn-danger"formaction="{% url 'teachers:delete' teacher.id %}" type="submit" value="Delete">
    <br>
<h3>Teacher current edition</h3>
    <table>
         <tr>
            <th>Id</th>
            <th>First name</th>
            <th>Last name</th>
            <th>Age</th>
            <th>Start work</th>
            <th>School</th>
        </tr>

        <tr>
            <td>{{ teacher.id }}</td>
            <td>{{ teacher.first_name }}</td>
            <td>{{ teacher.last_name }}</td>
            <td>{{ teacher.age }}</td>
            <td>{{ teacher.date_start_work }}</td>
            <td>{{ teacher.school }}</td>

        </tr>
    </table>
</form>

{% endblock %}

teachers/templates/teachers-list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>View teachers</title>
{% endblock %}

{% block content %}
<h2>Teachers</h2>
<form>
  {{form|crispy}}<br>
  <input class="btn btn-light" type="submit" value="Search">
  <input class="btn btn-primary"formaction="{% url 'teachers:create' %}" type="submit" value = 'Create'><br><br>
</form>
<table>
    <thead>
        <tr>
            <th>View</th>
            <th>Id</th>
            <th>First name</th>
            <th>Last name</th>
            <th>Age</th>
            <th>Start work</th>
            <th>School</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>

{% for teacher in teachers %}
    <tbody>
        <tr>
            <td><a href="{% url 'teachers:view' teacher.id %}">View</a></td>
            <td>{{ teacher.id }}</td>
            <td>{{ teacher.first_name }}</td>
            <td>{{ teacher.last_name }}</td>
            <td>{{ teacher.age }}</td>
            <td>{{ teacher.date_start_work }}</td>
            <td>{{ teacher.school }}</td>
            <td><a href="{% url 'teachers:edit' teacher.id%}">EDIT</a></td>
            <td><a href="{% url 'teachers:delete' teacher.id %}">DELETE</a></td>

        </tr>
    </tbody>
{% endfor %}
</table>
<br>
{% with list_objects=teachers %}
{% include 'includes/paginator.html' %}
{% endwith %}

{% endblock %}