accounts/urls.py
from accounts.views import AccountCreateView, AccountLoginView, AccountLogoutView,  AccountPasswordUpdate, \
    AccountUpdateView

from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('register/', AccountCreateView.as_view(), name="register"),
    path('login/', AccountLoginView.as_view(), name="login"),
    path('logout/', AccountLogoutView.as_view(), name="logout"),
    path('profile/', AccountUpdateView.as_view(), name="profile"),
    path('password/', AccountPasswordUpdate.as_view(), name="password"),


 ]

core/urls.py
from core.views import index

from django.contrib import admin  # noqa
from django.urls import path

app_name = 'core'

urlpatterns = [
  path('', index, name="index"),

 ]

groups/urls.py
from django.contrib import admin  # noqa
from django.urls import path

from groups.views import GroupCreateView, GroupUpdateView, delete_group, get_groups, view_group

from students.views import hello

app_name = 'groups'

urlpatterns = [
    path('', hello, name="hello"),
    path('create', GroupCreateView.as_view(), name="create"),
    path('list/', get_groups, name="list"),
    path('view/<int:id>', view_group, name="view"),
    path('edit/<int:id>', GroupUpdateView.as_view(), name="edit"),
    path('delete/<int:id>', delete_group, name="delete"),
 ]

lms/urls.py
import debug_toolbar

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('groups/', include('groups.urls')),
    path('accounts/', include('accounts.urls')),


]
urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.contrib import admin  # noqa
from django.urls import path

from students.views import StudentCreateView, StudentUpdateView, delete_student, \
                            generate_students, get_random, get_student, get_students, hello

app_name = 'students'

urlpatterns = [
    path('', hello, name="hello"),
    path('password/', get_random, name="password"),
    path('generate_students/', generate_students, name="gen_students"),
    path('students/', get_students, name="view_all_students"),
    path('list/', get_student, name="list"),
    path('create/', StudentCreateView.as_view(), name="create"),
    path('edit/<uuid:uuid>', StudentUpdateView.as_view(), name="edit"),
    path('delete/<uuid:uuid>', delete_student, name="delete"),

 ]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
{% block title %}

    <title>LMS</title>
{% endblock %}


</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top navbar-expand-lg navbar-dark bg-primary font-weight-bold">
   <div class="container">
    <a class="navbar-brand" href="{% url 'core:index' %}">LMS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-link" href="{% url 'groups:list' %}">Groups</a>
      <a class="nav-link" href="{% url 'teachers:list' %}">Teachers</a>
      <a class="nav-link" href="{% url 'students:list' %}">Students</a>
    <ul class="navbar-nav ">
       {%  if user.is_authenticated %}
        <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:profile' %}">Profile ({{user}})<img class="rounded-circle p-1 m-1" width="40" height="40"  src="{{ user.profile.image.url }}"></a>
                  </li>

                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a>
                  </li>
            {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                  </li>

                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                  </li>
            {% endif %}

    </ul>
    </div>
  </div>
   </div>
</nav>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: center;
  padding: 8px;
}

tr:nth-child(odo) {
  background-color: #dddddd;
}
</style>


 <div class="container">

<div>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="{{ message.tags }}">
                {{ message|safe }}
                <a href="#" class="close">✖</a>
            </li>
        {% endfor %}
    </ul>
{% endif %}
</div>




<h1>LMS</h1>

{% block content %}
{% endblock %}

 </div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'students:list' %}">Students</a><br>
    <a href="{% url 'teachers:list' %}">Teachers</a><br>
    <a href="{% url 'groups:list' %}">Groups</a><br><br>
    <a href="admin/">Admin</a><br>


{% endblock %}